CREATE DATABASE IF NOT EXISTS tms;


USE tms;


CREATE TABLE IF NOT EXISTS users (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    taskId INT AUTO_INCREMENT PRIMARY KEY,
    taskName VARCHAR(255) NOT NULL,
    is_Done BOOLEAN DEFAULT 0,
    userId INT,
    FOREIGN KEY (userId) REFERENCES users(userId)
);
